### ISSUE TITLE
TODO-list

### ISSUE THREAD

**Issue by haampie** [haampie/ArnoldiMethod.jl#67]
There is still some work to be done:

- [ ] Reordering of the Schur form such that eigenvalues closest to the specified target appear first
- [ ] Purging / removing eigenvalues that are unwanted (http://www.netlib.org/utk/people/JackDongarra/etemplates/node232.html)
- [ ] B-inner product for generalized problems (#50)
- [ ] Tricks: improve eigenvector approximation in certain spectral transformations (http://www.netlib.org/utk/people/JackDongarra/etemplates/node233.html)
